In [1]:
import torch

In [3]:
x = torch.arange(12)             #生成向量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()          # 获取张量元素个数  number of elements

12

In [6]:
# 改变形状
x = x.reshape(3,4)

In [7]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.tensor([[[1,2,3],[4,5,6]]]).shape

torch.Size([1, 2, 3])

In [11]:
torch.Size

torch.Size

In [12]:
# 算术运算

In [13]:
x = torch.tensor([1.0,2,3,5])

In [14]:
y= torch.tensor([2.0,5,6,1])
x + y, x - y, x * y, x / y, x**y

(tensor([3., 7., 9., 6.]),
 tensor([-1., -3., -3.,  4.]),
 tensor([ 2., 10., 18.,  5.]),
 tensor([0.5000, 0.4000, 0.5000, 5.0000]),
 tensor([  1.,  32., 729.,   5.]))

In [15]:
 x = torch.arange(12, dtype=torch.float32).reshape(3,4)

In [16]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
y = torch.tensor([[1,2,3,4],[2,3,4,5],[7,2,9,7]])

In [18]:
y

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [7, 2, 9, 7]])

In [19]:
torch.cat((x,y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  2.,  3.,  4.],
        [ 2.,  3.,  4.,  5.],
        [ 7.,  2.,  9.,  7.]])

In [20]:
torch.cat((x,y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  5.],
        [ 8.,  9., 10., 11.,  7.,  2.,  9.,  7.]])

In [21]:
z = torch.tensor([[[1,1,1],[1,1,1],[1,1,1]],[[1,2,3],[4,5,6],[7,8,9]]])

In [22]:
z

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [23]:
w = torch.tensor([[[0,0,0],[0,0,0],[0,0,0]]])

In [24]:
w

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [25]:
torch.cat((z,w),dim = 0)

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [26]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
y

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [7, 2, 9, 7]])

In [30]:
x.sum

<function Tensor.sum>

In [31]:
x.sum()

tensor(66.)

In [32]:
# 形状不同，也可进行运算  广播机制
# 必须相同维度，如果形状不一致，会自动不齐进行运算
a = torch.arange(3)
a

tensor([0, 1, 2])

In [33]:
a = a.reshape(3,1)
a

tensor([[0],
        [1],
        [2]])

In [34]:
b = torch.arange(2).reshape(1,2)

In [35]:
b

tensor([[0, 1]])

In [36]:
a ,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [37]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [38]:
x


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [39]:
x[-1]

tensor([ 8.,  9., 10., 11.])

In [40]:
x[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [41]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
x[1,2] = 0.0

In [43]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  0.,  7.],
        [ 8.,  9., 10., 11.]])

In [44]:
x[0:2,:]=12

In [45]:
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [46]:
x[:,1:2]=0

In [47]:
x

tensor([[12.,  0., 12., 12.],
        [12.,  0., 12., 12.],
        [ 8.,  0., 10., 11.]])

In [48]:
id(x)              

139781363730608

In [49]:
id(y)

139781364190400

In [50]:
y = y + x

In [51]:
id(y)

139781363855168

In [52]:
id(x)

139781363730608

In [53]:
id(y)

139781363855168

In [54]:
x,y

(tensor([[12.,  0., 12., 12.],
         [12.,  0., 12., 12.],
         [ 8.,  0., 10., 11.]]),
 tensor([[13.,  2., 15., 16.],
         [14.,  3., 16., 17.],
         [15.,  2., 19., 18.]]))

In [55]:
x[:] = x + y

In [56]:
id(x)

139781363730608

In [57]:
a = x.numpy()

In [58]:
a

array([[25.,  2., 27., 28.],
       [26.,  3., 28., 29.],
       [23.,  2., 29., 29.]], dtype=float32)

In [59]:
type(a)

numpy.ndarray

In [60]:
a = torch.tensor([3.5])

In [61]:
a

tensor([3.5000])

In [62]:
a,item()

NameError: name 'item' is not defined