In [1]:
import torch

In [2]:
x = torch.tensor([3.0])
y = torch.tensor([2.0])

In [3]:
x,y

(tensor([3.]), tensor([2.]))

In [4]:
x + y

tensor([5.])

In [5]:
x * y

tensor([6.])

In [6]:
x / y, x**y

(tensor([1.5000]), tensor([9.]))

In [7]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [8]:
x[3]

tensor(3)

In [9]:
x[2]

tensor(2)

In [10]:
len(x)

4

In [11]:
len(y)

1

In [13]:
A = torch.arange(20).reshape(5,4)

In [14]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [18]:
A.T                #矩阵转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [19]:
A == A.T

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1

In [26]:
A = torch.arange(20,dtype = torch.float32).reshape(5,4)
B = A.clone()  # 通过分配新内存，将A的副本分配给B
A, B, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [24]:
B [:,2] = 2

In [25]:
B

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  2.,  7.],
        [ 8.,  9.,  2., 11.],
        [12., 13.,  2., 15.],
        [16., 17.,  2., 19.]])

In [23]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [27]:
a = 2
x = torch.arange(24).reshape(2,3,4)

In [28]:
a,x

(2,
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]))

In [29]:
a + x

tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])

In [30]:
a * x

tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])

In [31]:
(a * x).shape

torch.Size([2, 3, 4])

In [32]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [33]:
x.sum()

tensor(6)

In [34]:
x = torch.arange(40).reshape(2,5,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [36]:
x.sum(axis=1)

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [37]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [38]:
x.sum()

tensor(780)

In [39]:
x.sum(axis = 0)

tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])

In [40]:
x.sum(axis = 1)

tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])

In [41]:
x.sum(axis = [0,1])

tensor([180, 190, 200, 210])

In [42]:
x.sum(axis = 2)

tensor([[  6,  22,  38,  54,  70],
        [ 86, 102, 118, 134, 150]])

In [43]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [44]:
x.mean()

RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Long instead.

In [45]:
x.shape()

TypeError: 'torch.Size' object is not callable

In [46]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])

In [47]:
x.shape

torch.Size([2, 5, 4])

In [48]:
x.type

<function Tensor.type>

In [49]:
x.type()

'torch.LongTensor'

In [52]:
x.reshape(2,5,4,dtype = torch.float64)

TypeError: reshape() got an unexpected keyword argument 'dtype'

In [53]:
x.dtype=torch.float32

AttributeError: attribute 'dtype' of 'torch._C._TensorBase' objects is not writable

In [57]:
x = x.float()

AttributeError: 'builtin_function_or_method' object has no attribute 'float'

In [55]:
x

<function Tensor.float>

In [56]:
x

<function Tensor.float>

In [6]:
x = torch.arange(8).reshape(2,4)
x

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [61]:
float(x)

ValueError: only one element tensors can be converted to Python scalars

In [67]:
x = x.float()
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [69]:
x.mean()

tensor(3.5000)

In [70]:
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [71]:
x.numble

AttributeError: 'Tensor' object has no attribute 'numble'

In [72]:
x.numble()

AttributeError: 'Tensor' object has no attribute 'numble'

In [73]:
x.numel()

8

In [74]:
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [75]:
x.mean(axis = 0)

tensor([2., 3., 4., 5.])

In [76]:
x.mean(axis = 1)

tensor([1.5000, 5.5000])

In [77]:
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [78]:
x.sum(axis=0)

tensor([ 4.,  6.,  8., 10.])

In [79]:
x.sum(axis=1)

tensor([ 6., 22.])

In [80]:
x.sum(axis=0,keepdims=True)

tensor([[ 4.,  6.,  8., 10.]])

In [81]:
x.sum(axis=1,keepdims=True)

tensor([[ 6.],
        [22.]])

In [82]:
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [84]:
x/x.sum(axis=0,keepdims=True)

tensor([[0.0000, 0.1667, 0.2500, 0.3000],
        [1.0000, 0.8333, 0.7500, 0.7000]])

In [85]:
x/x.sum(axis=1,keepdims=True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182]])

In [86]:
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [90]:
x.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.]])

In [91]:
x.cumsum(axis=1)

tensor([[ 0.,  1.,  3.,  6.],
        [ 4.,  9., 15., 22.]])

In [92]:
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [4]:
a = torch.arange(4).reshape(4,1)


In [5]:
a.size(),a

(torch.Size([4, 1]),
 tensor([[0],
         [1],
         [2],
         [3]]))

In [106]:
torch.mv(x,a)

RuntimeError: vector + matrix @ vector expected, got 1, 2, 2

In [3]:
a

NameError: name 'a' is not defined

In [108]:
x = torch.arange(12).reshape(3,4)

In [2]:
x

NameError: name 'x' is not defined

In [113]:
torch.mv(x,a)

RuntimeError: vector + matrix @ vector expected, got 1, 2, 2

In [112]:
x.shape,a.shape,

(torch.Size([3, 4]), torch.Size([4, 1]))

In [114]:
a.reshape(1,4)

tensor([[0, 1, 2, 3]])

In [115]:
a.size

<function Tensor.size>

In [116]:
a.sape

AttributeError: 'Tensor' object has no attribute 'sape'

In [117]:
a.shape

torch.Size([4, 1])

In [7]:
A = torch.arange(20).reshape(5,4)

In [8]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
A.shape

torch.Size([5, 4])

In [17]:
x = torch.arange(4).reshape(4)
x,x.shape

(tensor([0, 1, 2, 3]), torch.Size([4]))

In [18]:
torch.mv(A,x)

tensor([ 14,  38,  62,  86, 110])

In [19]:
# 矩阵乘法
B = torch.ones(4,3)

In [20]:
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
A.float()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [26]:
torch.mm(A.float(),B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [32]:
# 范数
a = torch.ones(4,9)
a

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
torch.norm(torch.ones((4,9)))

tensor(6.)

In [36]:
a = torch.arange(20).reshape(5,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [37]:
torch.sum(a,axis=0)

tensor([40, 45, 50, 55])

In [38]:
torch.sum(a,axis=1)

tensor([ 6, 22, 38, 54, 70])

In [44]:
b = torch.arange(12).reshape(3,2,2)

In [45]:
b

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [46]:
b.shape

torch.Size([3, 2, 2])

In [47]:
torch.sum(b,axis=0)

tensor([[12, 15],
        [18, 21]])

In [48]:
torch.sum(b,axis=1)

tensor([[ 2,  4],
        [10, 12],
        [18, 20]])

In [49]:
torch.sum(b,axis=2)

tensor([[ 1,  5],
        [ 9, 13],
        [17, 21]])

In [51]:
torch.sum(b,axis=0,keepdim=True)

tensor([[[12, 15],
         [18, 21]]])

In [5]:
a = torch.arange(12).reshape(2,3,2)

In [6]:
a

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [7]:
a.sum(axis=1)

tensor([[ 6,  9],
        [24, 27]])

In [11]:
a.sum(axis=1,keepdim=True)

tensor([[[ 6,  9]],

        [[24, 27]]])

In [8]:
a.sum(axis=0)

tensor([[ 6,  8],
        [10, 12],
        [14, 16]])

In [12]:
a.sum(axis=0,keepdim=True)

tensor([[[ 6,  8],
         [10, 12],
         [14, 16]]])

In [9]:
a.sum(axis=2)

tensor([[ 1,  5,  9],
        [13, 17, 21]])

In [10]:
a.sum(axis=2,keepdim=True)

tensor([[[ 1],
         [ 5],
         [ 9]],

        [[13],
         [17],
         [21]]])