In [24]:
import torch

In [25]:
x = torch.arange(4.0)

In [26]:
x

tensor([0., 1., 2., 3.])

In [27]:
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [28]:
x.grad

In [32]:
# y = 2 xTx   内积  2乘x的平方   求导为4x

y = 2 * torch.dot(x, x)

In [19]:
y

tensor(28., grad_fn=<MulBackward0>)

In [34]:
y.backward()

In [35]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [36]:
x.grad == 4*x

tensor([True, True, True, True])

In [37]:
# pytorch 会累积梯度，新的计算需要清除之前的值
x.grad.zero_()
y = x.sum()

In [38]:
y

tensor(6., grad_fn=<SumBackward0>)

In [39]:
y.backward()

In [40]:
x.grad

tensor([1., 1., 1., 1.])

In [45]:
a = torch.arange(3)
a

tensor([0, 1, 2])

In [44]:
a.sum()

tensor(3)

In [46]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [53]:
a = torch.randn(size=(),requires_grad=True)
a

tensor(0.2500, requires_grad=True)

In [54]:
f(a)

tensor(1024.0292, grad_fn=<MulBackward0>)

In [55]:
d = f(a)

In [56]:
d

tensor(1024.0292, grad_fn=<MulBackward0>)

In [57]:
d.backward()

In [58]:
a.grad

tensor(4096.)

In [59]:
a.grad == d / a

tensor(True)