In [3]:
import os
import torch 

In [4]:
os.makedirs(os.path.join('.','data'),exist_ok=True)   # 创建文件夹

In [5]:
datafile = os.path.join('.','data','house_tiny.csv')  # 要创建的文件名

In [6]:
with open(datafile,'w') as f:
    f.write('NumRooms,Alley,Price\n')   #列名
    f.write('NA,Pava,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,140000')
    
    

In [7]:
import pandas as pd

In [8]:
data = pd.read_csv(datafile)
data

NumRooms Alley   Price
0       NaN  Pava  127500
1       2.0   NaN  106000
2       4.0   NaN  140000

In [9]:
#  缺失值处理   插值和删除

In [10]:
inputs = data.iloc[:,0:2]
inputs

NumRooms Alley
0       NaN  Pava
1       2.0   NaN
2       4.0   NaN

In [11]:
inputs

NumRooms Alley
0       NaN  Pava
1       2.0   NaN
2       4.0   NaN

In [12]:
outputs = data.iloc[:,2]
outputs

0    127500
1    106000
2    140000
Name: Price, dtype: int64

In [13]:
inputs = inputs.fillna(inputs.mean())      # 空值填充
inputs

/tmp/ipykernel_8097/1241018506.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())      # 空值填充


NumRooms Alley
0       3.0  Pava
1       2.0   NaN
2       4.0   NaN

In [14]:
inputs

NumRooms Alley
0       3.0  Pava
1       2.0   NaN
2       4.0   NaN

In [15]:
inputs = pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pava  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1

In [16]:
x

NameError: name 'x' is not defined

In [17]:
y

NameError: name 'y' is not defined

In [20]:
x= torch.tensor(inputs.values)

In [21]:
x

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.]], dtype=torch.float64)

In [22]:
a = torch.arange(12)

In [23]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
b = a.reshape(3,4)

In [25]:
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [26]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [28]:
b[:] = 2

In [29]:
b

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

In [30]:
s

NameError: name 's' is not defined

In [31]:
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
a.shape()

TypeError: 'torch.Size' object is not callable

In [33]:
a.shape


torch.Size([12])

In [34]:
b.shape

torch.Size([3, 4])

In [35]:
a.size

<function Tensor.size>

In [37]:
a.size()

torch.Size([12])

In [38]:
b.size()

torch.Size([3, 4])