In [1]:
import numpy as np

## 第一章习题

### Ex1：利用列表推导式写矩阵乘法

In [3]:
# 利用列表推导式写矩阵乘法
M1 = np.random.rand(2,3)
M2 = np.random.rand(3,4)
M1,M2

(array([[0.10958406, 0.77063955, 0.9518978 ],
        [0.22811659, 0.12594455, 0.21852894]]),
 array([[0.22537566, 0.56884439, 0.6750117 , 0.18096601],
        [0.09040277, 0.9782829 , 0.98823421, 0.91389511],
        [0.58408814, 0.87292112, 0.02602173, 0.25126145]]))

In [4]:
res = np.empty((M1.shape[0],M2.shape[1]))
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M2.shape[0]):
          item +=  M1[i][k] * M2[k][j]
        res[i][j] = item


In [9]:
res


array([[0.65035775, 1.64717147, 0.86031292, 0.96328992],
       [0.19043782, 0.44373077, 0.28413058, 0.21128935]])

In [8]:
M1@M2    # 矩阵乘法

array([[0.65035775, 1.64717147, 0.86031292, 0.96328992],
       [0.19043782, 0.44373077, 0.28413058, 0.21128935]])

In [12]:
# 改写成列表推导式
def my_fun1(M1,M2):
    res = np.empty((M1.shape[0],M2.shape[1]))
    for i in range(M1.shape[0]):
        for j in range(M2.shape[1]):
            item = 0
            for k in range(M2.shape[0]):
              item +=  M1[i][k] * M2[k][j]
            res[i][j] = item




SyntaxError: did you forget parentheses around the comprehension target? (985212621.py, line 12)

In [ ]:
[sum([(i*j) for i in M1] for j in M2.T )]

In [ ]:
[[sum([M1[i][k] * M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]


### Ex2: 计算卡方统计量

In [2]:
np.random.seed(1)
A = np.random.randint(10,20,(8,5))
A

array([[15, 18, 19, 15, 10],
       [10, 11, 17, 16, 19],
       [12, 14, 15, 12, 14],
       [12, 14, 17, 17, 19],
       [11, 17, 10, 16, 19],
       [19, 17, 16, 19, 11],
       [10, 11, 18, 18, 13],
       [19, 18, 17, 13, 16]])

In [4]:
A.sum(0),A.sum(1), A.sum()

(array([108, 120, 129, 126, 121]),
 array([77, 73, 67, 79, 73, 82, 70, 83]),
 604)

In [37]:
A.sum(1).reshape(-1, 1)

array([[77],
       [73],
       [67],
       [79],
       [73],
       [82],
       [70],
       [83]])

In [40]:
A.sum(0)*A.sum(1).reshape(-1, 1)

array([[ 8316,  9240,  9933,  9702,  9317],
       [ 7884,  8760,  9417,  9198,  8833],
       [ 7236,  8040,  8643,  8442,  8107],
       [ 8532,  9480, 10191,  9954,  9559],
       [ 7884,  8760,  9417,  9198,  8833],
       [ 8856,  9840, 10578, 10332,  9922],
       [ 7560,  8400,  9030,  8820,  8470],
       [ 8964,  9960, 10707, 10458, 10043]])

In [30]:
B = A.sum(0)*A.sum(1).reshape(-1, 1)/A.sum()


In [32]:
B

array([[13.76821192, 15.29801325, 16.44536424, 16.06291391, 15.42549669],
       [13.05298013, 14.50331126, 15.5910596 , 15.22847682, 14.62417219],
       [11.98013245, 13.31125828, 14.30960265, 13.97682119, 13.42218543],
       [14.12582781, 15.69536424, 16.87251656, 16.48013245, 15.82615894],
       [13.05298013, 14.50331126, 15.5910596 , 15.22847682, 14.62417219],
       [14.66225166, 16.29139073, 17.51324503, 17.10596026, 16.42715232],
       [12.51655629, 13.90728477, 14.95033113, 14.60264901, 14.02317881],
       [14.8410596 , 16.49006623, 17.72682119, 17.31456954, 16.62748344]])

In [31]:
((A-B)**2/B).sum()

20.1161991410316

### Ex3: 月度销量情况统计

In [1]:
import numpy as np
np.load('data/ch1/shop')

## 第二章习题

In [1]:
# 口袋妖精
import pandas as pd
df = pd.read_csv('data/pokemon.csv')

In [3]:
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  
0         65       65     45  
1         80       80     60  
2        100      100     80  
3        122      120     80  
4         60       50     65  
..       ...      ...    ...  
795      100      150     50  
796      160      110    110  
797      150      130     70  
798      170      130     80  
799      130       90     70  

[800 rows x 11 columns]

In [13]:
# 1. 对 HP, Attack, Defense, Sp. Atk, Sp. Def, Speed 进行加总，验证是否为 Total 值。
total1 = df[df.columns[5:11]].sum(axis=1)

In [16]:
df['Total'] = total1

In [ ]:
"""
2. 对于 # 重复的妖怪只保留第一条记录，解决以下问题：
(a) 求第一属性的种类数量和前三多数量对应的种类
(b) 求第一属性和第二属性的组合种类
(c) 求尚未出现过的属性组合
"""



In [17]:
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  
0         65       65     45  
1         80       80     60  
2        100      100     80  
3        122      120     80  
4         60       50     65  
..       ...      ...    ...  
795      100      150     50  
796      160      110    110  
797      150      130     70  
798      170      130     80  
799      130       90     70  

[800 rows x 11 columns]

In [18]:
df['#'].value_counts()

479    6
386    4
710    4
711    4
646    3
      ..
250    1
251    1
252    1
253    1
721    1
Name: #, Length: 721, dtype: int64

In [2]:
df2 = df.drop_duplicates(['#'])

In [3]:
df2.value_counts(['#'])

#  
1      1
475    1
477    1
478    1
479    1
      ..
243    1
244    1
245    1
246    1
721    1
Length: 721, dtype: int64

In [22]:
df2

#                 Name   Type 1  Type 2  Total   HP  Attack  Defense  \
0      1            Bulbasaur    Grass  Poison    318   45      49       49   
1      2              Ivysaur    Grass  Poison    405   60      62       63   
2      3             Venusaur    Grass  Poison    525   80      82       83   
4      4           Charmander     Fire     NaN    309   39      52       43   
5      5           Charmeleon     Fire     NaN    405   58      64       58   
..   ...                  ...      ...     ...    ...  ...     ...      ...   
793  717              Yveltal     Dark  Flying    680  126     131       95   
794  718     Zygarde50% Forme   Dragon  Ground    600  108     100      121   
795  719              Diancie     Rock   Fairy    600   50     100      150   
797  720  HoopaHoopa Confined  Psychic   Ghost    600   80     110       60   
799  721            Volcanion     Fire   Water    600   80     110      120   

     Sp. Atk  Sp. Def  Speed  
0         65       65     45  
1         80       80     60  
2        100      100     80  
4         60       50     65  
5         80       65     80  
..       ...      ...    ...  
793      131       98     99  
794       81       95     95  
795      100      150     50  
797      150      130     70  
799      130       90     70  

[721 rows x 11 columns]

In [25]:
# (a) 求第一属性的种类数量和前三多数量对应的种类
df2['Type 1'].nunique()

18

In [28]:
df2['Type 1'].value_counts()

Water       105
Normal       93
Grass        66
Bug          63
Fire         47
Psychic      47
Rock         41
Electric     36
Ground       30
Poison       28
Dark         28
Fighting     25
Dragon       24
Ghost        23
Ice          23
Steel        22
Fairy        17
Flying        3
Name: Type 1, dtype: int64

In [29]:
df2['Type 1'].value_counts().head(3)

Water     105
Normal     93
Grass      66
Name: Type 1, dtype: int64

In [15]:
# (b) 求第一属性和第二属性的组合种类
# df2[['Type 1','Type 2']].nunique()
attr_dup = df2.drop_duplicates(['Type 1', 'Type 2'])
attr_dup.shape[0]

143

In [4]:
# (c) 求尚未出现过的属性组合
type1 = df2['Type 1'].unique()
type2 = df2['Type 2'].unique()

In [5]:
type1,type2

(array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
        'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
        'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object),
 array(['Poison', nan, 'Flying', 'Ground', 'Fairy', 'Grass', 'Fighting',
        'Psychic', 'Steel', 'Ice', 'Rock', 'Water', 'Electric', 'Fire',
        'Dragon', 'Dark', 'Ghost', 'Bug', 'Normal'], dtype=object))

In [8]:
df3 = pd.DataFrame
df3

pandas.core.frame.DataFrame

In [20]:
df4 = attr_dup[['Type 1','Type 2'],index = False]
df4

SyntaxError: invalid syntax (48926573.py, line 1)

In [19]:
df4.apply

<bound method DataFrame.apply of       Type 1  Type 2
0      Grass  Poison
4       Fire     NaN
6       Fire  Flying
9      Water     NaN
13       Bug     NaN
..       ...     ...
773     Rock   Fairy
778    Ghost   Grass
790   Flying  Dragon
797  Psychic   Ghost
799     Fire   Water

[143 rows x 2 columns]>

In [10]:
for i in type1:
    for j in type2:
        print(i,j)

Grass Poison
Grass nan
Grass Flying
Grass Ground
Grass Fairy
Grass Grass
Grass Fighting
Grass Psychic
Grass Steel
Grass Ice
Grass Rock
Grass Water
Grass Electric
Grass Fire
Grass Dragon
Grass Dark
Grass Ghost
Grass Bug
Grass Normal
Fire Poison
Fire nan
Fire Flying
Fire Ground
Fire Fairy
Fire Grass
Fire Fighting
Fire Psychic
Fire Steel
Fire Ice
Fire Rock
Fire Water
Fire Electric
Fire Fire
Fire Dragon
Fire Dark
Fire Ghost
Fire Bug
Fire Normal
Water Poison
Water nan
Water Flying
Water Ground
Water Fairy
Water Grass
Water Fighting
Water Psychic
Water Steel
Water Ice
Water Rock
Water Water
Water Electric
Water Fire
Water Dragon
Water Dark
Water Ghost
Water Bug
Water Normal
Bug Poison
Bug nan
Bug Flying
Bug Ground
Bug Fairy
Bug Grass
Bug Fighting
Bug Psychic
Bug Steel
Bug Ice
Bug Rock
Bug Water
Bug Electric
Bug Fire
Bug Dragon
Bug Dark
Bug Ghost
Bug Bug
Bug Normal
Normal Poison
Normal nan
Normal Flying
Normal Ground
Normal Fairy
Normal Grass
Normal Fighting
Normal Psychic
Normal Steel
Normal