## 1.python基础

### 1.1列表推导式与条件赋值

In [2]:
#  
# 数字序列
L = []
def my_fun(x):
    return 2*x

In [5]:
for i in range(5):
  L.append(my_fun(i))

In [7]:
# 列表推导式进行写法上的简化
[my_fun(i) for i in range(5)]

[0, 2, 4, 6, 8]

In [8]:
# 第一个for外循环第二个for内循环
[m +'_'+ n for m in ['a','b']for n in ['c','d']]

['a_c', 'a_d', 'b_c', 'b_d']

In [9]:
#  条件赋值语句 value = a if condition else b:
value = 'cat' if 2>1 else 'dog'

In [10]:
value

'cat'

In [11]:
if 2>1 :
    value2 = 'cat'
else:
    value2 = 'dog'

In [12]:
value2

'cat'

In [25]:
# 截断 列表中超过5的元素
L = [1,5,2,66,7,8,1,4,55]
result = []
# [result.append(i) if i >5 for i in L]
result = [i if i>5 else 0 for i in  L]

In [26]:
result

[0, 0, 0, 66, 7, 8, 0, 0, 55]

### 1.2 匿名函数与map方法

In [13]:
# 定义映射关系清晰简单的函数
my_func = lambda x: 2*x
my_func(3),
my_func([0,1,2,3,4])

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [11]:
multi_para_func = lambda a, b: a + b
multi_para_func(1,2)


[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [5]:
[(lambda x:2*x) (i) for i in range(5)]

[0, 2, 4, 6, 8]

In [20]:
list(map(lambda x:2*x ,range(5)))

[0, 2, 4, 6, 8]

In [10]:
[(lambda x:2*x) (5)]

[10]

In [16]:
def myfunc(n):
  return lambda a : a * n

In [17]:
dou = myfunc(2)

In [18]:
dou(3)

6

In [28]:
list(map(lambda x:x*2,[1,2,3,4]))

[2, 4, 6, 8]

### 1.3 zip与enumerate
  
&emsp;zip函数打包多个可迭代对象成一个元祖，生成元素个数与最短的列表一致。可用来并行计算

In [34]:
l1, l2, l3 = list('abc'),list('def'),list('hi')

In [35]:
l1,l2,l3

(['a', 'b', 'c'], ['d', 'e', 'f'], ['h', 'i'])

In [36]:
list(zip(l1,l2,l3)),tuple(zip(l1,l2,l3))

([('a', 'd', 'h'), ('b', 'e', 'i')], (('a', 'd', 'h'), ('b', 'e', 'i')))

In [37]:
# 使用for循环来并行迭代多个序列
for i,j,k in list(zip(l1,l2,l3)):
    print(i,j,k)

a d h
b e i


In [38]:
# enumerate ：特殊的打包，
l = list('abcd')
for index,value in enumerate(l):
    print (index,value)

0 a
1 b
2 c
3 d


In [40]:
list(enumerate(l))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]

In [43]:
# 使用zip实现enumerate
for index,value in zip(range(len(l)),l):
    print(index,value)

0 a
1 b
2 c
3 d


In [42]:
range(len(l1))

range(0, 3)

In [26]:
# zip 还可以将两个列表建立字典映射
l1 = [1,2,3]
l2 = ['a','b','c']
zipped1 = dict(zip(l1,l2))
zipped1

{1: 'a', 2: 'b', 3: 'c'}

In [22]:
# 解压缩
l1 = [1,2,3]
l2 = ['a','b','c']
ziped = list(zip(l1,l2))

In [23]:
list(zip(*ziped))

[(1, 2, 3), ('a', 'b', 'c')]

## 2.numpy 基础

In [2]:
import numpy as np

In [8]:
#  数组
b = np.array([1,2,3])

In [6]:
a = list('ass')

In [11]:
b.shape

(3,)

In [14]:
# 特殊数组生成  np.linespace(起始，终止，样本个数) 等差数列
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
# arange 起始，终止，布长 （终止不包括）
np.arange(1,5,2)

array([1, 3])

In [4]:
#  t特殊矩阵 zeros eye  full
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# 生成对角阵，主对角线上元素为1，其余位置均为0
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
# 偏移一个单位的伪单位矩阵
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [7]:
# 创建矩阵 并用指定值填满
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [8]:
np.full((2,3),[1,1,1])

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
# 随机矩阵np.random   默认服从0-1分布
np.random.rand(3)  ## 生成服从 0-1 均匀分布的三个随机数


array([0.14745791, 0.35167099, 0.06779451])

In [10]:
np.random.rand(3,3)

array([[0.55330281, 0.27486468, 0.29976388],
       [0.49207204, 0.69657092, 0.96201918],
       [0.47324776, 0.11166501, 0.88354218]])

In [11]:
# 调整为 a-b上均匀分布
a, b= 5, 15
(b - a)* np.random.rand(3) + a

array([ 5.26215482, 11.87351318, 13.03876358])

In [14]:
# 方差为 σ2 均值为 µ 的一元正态分布

sigma, mu = 2.5, 3
mu + np.random.randn(3) * sigma 

array([4.59096995, 1.60915927, 1.48557989])

In [15]:
# randint 生成随机整数的最小值和最大值和维度大小
low,high,size = 5,15,(2,2)
np.random.randint(low,high,size)

array([[ 6, 14],
       [ 5, 11]])

In [16]:
(high-low) * np.random.rand(2,2) + low

array([[ 8.27721684,  8.69541428],
       [10.85608642, 14.65661205]])